name: Build and Release APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  ANDROID_COMPILE_SDK: 29
  ANDROID_BUILD_TOOLS: 29.0.3
  ANDROID_SDK_TOOLS: 6200805

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Android SDK
        uses: actions/setup-android@v1
        with:
          android-sdk-version: ${{ env.ANDROID_SDK_TOOLS }}

      - name: Build APK
        run: |
          export ANDROID_HOME=${{ env.ANDROID_HOME }}
          export PATH=$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
          echo y | android update sdk --no-ui --all --filter "platform-tools"
          echo y | android update sdk --no-ui --all --filter "build-tools-${{ env.ANDROID_BUILD_TOOLS }}"
          echo y | android update sdk --no-ui --all --filter "android-${{ env.ANDROID_COMPILE_SDK }}"
          ./gradlew assembleDebug

      - name: Publish APK to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive

  create_release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
